name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
            java-version: '8'
            distribution: 'adopt'
            server-id: github
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Publish package
        run: ./mvnw -B release:prepare release:perform -Dbuild.location=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
